language: python
python: 3.6

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache/pip"
    - "$HOME/.local/bin"

before_install:
  - sudo apt install figlet
  - nvm install

install:
  - npm ci

script:
  - ./awesome.sh
