language: python
python: 3.6

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache/pip"
    - "$HOME/.local/bin"

before_install:
  - nvm install

install:
  - npm ci
