language: python
python: 3.6
dist: xenial

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache/pip"
    - "$HOME/.local/bin"

before_install:
  - sudo apt update
  - sudo apt install figlet -y
  - nvm install

install:
  - npm i -g codecov
  - npm ci

script:
  - npm test

after_success:
  - ./awesome.sh

after_failure:
  - ./loser.sh
