version: '3'

services:
    dev:
        image: node:10-alpine
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: npm start
        ports:
            - 8080:3000
